# Uncomment the next line to define a global platform for your project

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # Pods for OneSignalNotificationServiceExtension
  
end

target 'qposts' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # project 'qposts.xcodeproj'
  # platform :ios, '9.0'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'GoogleIDFASupport'



  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'qpostsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'qposts-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qposts-tvOS

  target 'qposts-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
